@startuml C4-context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
Person(customer, "Customer/Patient", "A person in need of health care covered by the insurance.")
Person(claimhandler, "Claim handler", "A person handling the claim")
System(RSA_TRA, "Travel Coverage Search API", "Policy validation service")
System(NCP,"Nordic Care Platform", "System to support intake, steering and booking of health and travel related claims")
System(SubAPI, "Submission API", "API to submit all types of claims to")
'System(HealthAPI, "Health API", "REST API to provide partners with coverage validation")
'System(Partner, "Hjemmelegene", "Provides online doctor consultation")
System(WP, "Waypoint", "Core insurance and claim system")

Rel(customer,NCP, "Reports a health claim using")
Rel(NCP, RSA_TRA, "Reads travel coverage data from")
Rel(NCP, SubAPI, "Submit travel claim to")
Rel(SubAPI, WP, "Register claim in")
Rel(claimhandler, WP, "Handles claim in")
'Rel(NCP, HealthAPI, "Send policy coverage data to")
'Rel(Partner, HealthAPI, "Ask for policy validation")
@enduml