@startuml PlantUML demo
skinparam Style strictuml
Erik -> Helge : Check out PlantUML
Helge -> Erik : Wow! Now I love documentation too!
Helge -> Confluence : Adding my documentation here
Erik -> Helge: Nice!
@enduml